### Merging Polymod classes

In [1]:
import pandas as pd
import numpy as np

In [2]:
Polymod_data = pd.read_csv("./Data/Physical_Contacts_Polymod.csv", header = 1, index_col = 0)
Polymod_data.rename(columns={'00-04': '0-4', '|05-09|': '5-9', '|70+|': '70+'}, 
                    index={'00-04': '0-4', '|05-09|': '5-9', '|70+|': '70+'}, inplace = True)

Integrating age classes of contacts together

In [7]:
Deaths = pd.read_csv("Data//death_rate_7_age_groups_1982-2018.csv")
Deaths.iloc[:,0]

0        0
1      1-4
2      5-9
3    10-14
4    15-19
5    20-29
6      30+
7    total
Name: Age, dtype: object

In [93]:
Poly_4 = Polymod_data.iloc[0:4, 0:4]

In [94]:
Polymod_data.iloc[0:6, 0:6]

#we will merge the last 2 columns and rows

0-4   5-9  10-14  15-19  20-24  25-29
age of contact                                        
0-4             1.49  0.59   0.25   0.18   0.42   0.61
5-9             0.74  3.82   0.53   0.44   0.37   0.42
10-14           0.36  0.73   3.19   0.79   0.17   0.14
15-19           0.26  0.22   0.52   3.10   0.85   0.12
20-24           0.39  0.19   0.09   0.38   1.32   0.49
25-29           0.53  0.37   0.11   0.20   0.58   0.64

In [99]:
"""
I average the two columns that is I make an average of the number of contacts in age class 20-24
and class 25-29 towards any other age class

For rows, I instead sum over rows to cumulate the number of contacts with all people in the two classes when interviewing
partecipants od another age.

"""
merge_20_29_col = np.asarray(np.sum(Polymod_data.iloc[:, 4:6], axis = 1)/2)[0:4]

merge_20_29_row = np.asarray(np.sum(Polymod_data.iloc[4:6, :], axis = 0))[0:6]
print(merge_20_29_row)

merge_20_29_row = np.append(merge_20_29_row[0:4], np.mean(merge_20_29_row[4:6]))
print(merge_20_29_row)

[0.92 0.56 0.2  0.58 1.9  1.13]
[0.92  0.56  0.2   0.58  1.515]


In [100]:
Poly_4

0-4   5-9  10-14  15-19  20-29
age of contact                                 
0-4             1.49  0.59   0.25   0.18  0.515
5-9             0.74  3.82   0.53   0.44  0.395
10-14           0.36  0.73   3.19   0.79  0.155
15-19           0.26  0.22   0.52   3.10  0.485
20-29           0.92  0.56   0.20   0.58  1.515

In [97]:
Poly_5 = Poly_4

Poly_5["20-29"] = merge_20_29_col
Poly_5.loc["20-29"] = merge_20_29_row

In [101]:
Poly_5

0-4   5-9  10-14  15-19  20-29
age of contact                                 
0-4             1.49  0.59   0.25   0.18  0.515
5-9             0.74  3.82   0.53   0.44  0.395
10-14           0.36  0.73   3.19   0.79  0.155
15-19           0.26  0.22   0.52   3.10  0.485
20-29           0.92  0.56   0.20   0.58  1.515

Adding last row for 30+

In [102]:
Poly_6 = Poly_5

In [112]:
merge_30_col = np.asarray(np.sum(Polymod_data.iloc[:, 6:15], axis = 1)/9)[0:4]
#adding 20 29
merge_30_col = np.append(merge_30_col, np.sum(np.asarray(np.sum(Polymod_data.iloc[:, 6:15], axis = 1)/9)[4:6]))

merge_30_row = np.asarray(np.sum(Polymod_data.iloc[6:15, :], axis = 0))
print(merge_30_row)

merge_30_all_row = np.append(merge_30_row[0:4], np.mean(merge_30_row[4:6]))
merge_30_all_row = np.append(merge_30_all_row, np.mean(merge_30_row[6:15]))

print(merge_30_all_row)

[2.94 2.84 2.21 1.86 1.96 1.99 2.25 2.47 2.32 2.63 1.55 2.09 1.99 1.82
 2.03]
[2.94       2.84       2.21       1.86       1.975      2.12777778]


In [113]:
Poly_6["30+"] = merge_30_col

In [117]:
Poly_6.loc["30+"] = merge_30_all_row

In [118]:
Poly_6

0-4   5-9  10-14  15-19  20-29       30+
age of contact                                           
0-4             1.49  0.59   0.25   0.18  0.515  0.301111
5-9             0.74  3.82   0.53   0.44  0.395  0.402222
10-14           0.36  0.73   3.19   0.79  0.155  0.308889
15-19           0.26  0.22   0.52   3.10  0.485  0.285556
20-29           0.92  0.56   0.20   0.58  1.515  0.417778
30+             2.94  2.84   2.21   1.86  1.975  2.127778

Creating a another column for <1 identical to the previous 0-4

In [131]:
np.asarray(Poly_7.iloc[0,:])

array([1.49      , 1.49      , 0.59      , 0.25      , 0.18      ,
       0.515     , 0.30111111])

In [133]:
Poly_7 = Poly_6
Poly_7.insert (0, "<1", Poly_7.iloc[:,0])

In [ ]:
first_line = np.asarray(Poly_7.iloc[0,:])
Poly_7.loc["<1"] = first_line

In [137]:
Poly_7.reindex(["<1", "0-4", "5-9", "10-14", "15-19", "20-29", "30+"])

<1   0-4   5-9  10-14  15-19  20-29       30+
age of contact                                                 
<1              1.49  1.49  0.59   0.25   0.18  0.515  0.301111
0-4             1.49  1.49  0.59   0.25   0.18  0.515  0.301111
5-9             0.74  0.74  3.82   0.53   0.44  0.395  0.402222
10-14           0.36  0.36  0.73   3.19   0.79  0.155  0.308889
15-19           0.26  0.26  0.22   0.52   3.10  0.485  0.285556
20-29           0.92  0.92  0.56   0.20   0.58  1.515  0.417778
30+             2.94  2.94  2.84   2.21   1.86  1.975  2.127778

In [138]:
Poly_7_new = Poly_7.rename(columns={'0-4': '1-4'}, index={'0-4': '1-4'})

In [140]:
Poly_7_new.reindex(["<1", "1-4", "5-9", "10-14", "15-19", "20-29", "30+"])

<1   1-4   5-9  10-14  15-19  20-29       30+
age of contact                                                 
<1              1.49  1.49  0.59   0.25   0.18  0.515  0.301111
1-4             1.49  1.49  0.59   0.25   0.18  0.515  0.301111
5-9             0.74  0.74  3.82   0.53   0.44  0.395  0.402222
10-14           0.36  0.36  0.73   3.19   0.79  0.155  0.308889
15-19           0.26  0.26  0.22   0.52   3.10  0.485  0.285556
20-29           0.92  0.92  0.56   0.20   0.58  1.515  0.417778
30+             2.94  2.94  2.84   2.21   1.86  1.975  2.127778

In [144]:
Poly_7_new.values

array([[1.49      , 1.49      , 0.59      , 0.25      , 0.18      ,
        0.515     , 0.30111111],
       [0.74      , 0.74      , 3.82      , 0.53      , 0.44      ,
        0.395     , 0.40222222],
       [0.36      , 0.36      , 0.73      , 3.19      , 0.79      ,
        0.155     , 0.30888889],
       [0.26      , 0.26      , 0.22      , 0.52      , 3.1       ,
        0.485     , 0.28555556],
       [0.92      , 0.92      , 0.56      , 0.2       , 0.58      ,
        1.515     , 0.41777778],
       [2.94      , 2.94      , 2.84      , 2.21      , 1.86      ,
        1.975     , 2.12777778],
       [1.49      , 1.49      , 0.59      , 0.25      , 0.18      ,
        0.515     , 0.30111111]])

In [145]:
Poly_7_new.to_csv('Data/Poly_7.csv', index = True)